// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function fib(n) {
  if (n === 0 || n === 1) {
    return 1;
  } else {
    return fib(n - 1 | 0) + fib(n - 2 | 0) | 0;
  }
}

console.log(fib(3));

function render(myColor) {
  if (myColor === "yellow") {
    console.log("Hello yellow!");
  } else if (myColor === "green") {
    console.log("Hello green!");
  } else {
    console.log("Hello blue!");
  }
  
}

var areYouCrushingIt = /* Yes */0;

var myColor = "Ruby";

exports.fib = fib;
exports.areYouCrushingIt = areYouCrushingIt;
exports.myColor = myColor;
exports.render = render;
/*  Not a pure module */
